# Generated by Django 2.0 on 2017-12-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0002_client_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmessage',
            name='client',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ClientMessage',
        ),
    ]
